<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SolutionOrders.Categories.Application\SolutionOrders.Categories.Application.csproj" />
    <ProjectReference Include="..\SolutionOrders.Categories.Domain\SolutionOrders.Categories.Domain.csproj" />
    <ProjectReference Include="..\SolutionOrders.Categories.Core\SolutionOrders.Categories.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
